apiVersion: apps/v1
kind: Deployment
metadata:
 name: my-web-deployment-replicas
 labels:
  app : my-k8s-applications
  env : prod
  owner: vikvo
spec:
 replicas: 3
 selector:
  matchLabels:
   project: cia
 template:
  metadata:
   labels:
    project: cia
  spec:
   containers:
    - name: cia-web
      image: vikvo11/k8sphp:latest
      ports:
       - containerPort: 80
